daw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('mysite.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/urls.py
from django.conf.urls import include, url
from . import views
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'mysite'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^report/$', views.report, name='report'),
    path('json/data1/', views.data1, name='data1'),
    path('json/data2/', views.data2, name='data2'),
    path('json/data3/', views.data3, name='data3'),
    path('json/data4/', views.data4, name='data4'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Luis Perez">
    <meta name="description" content="">
    {% block head %}
        <title>{% block title %}{% endblock %} - Turistify</title>
    {% endblock %}

    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {#    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>#}
    <link rel="stylesheet" href="{% static 'mysite/my_style.css' %}">

    <link rel="stylesheet" href="{% static 'mysite/galeria/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/galeria/css/icofont.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/galeria/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/galeria/css/animate.css' %}">
    <!-- Main-Stylesheets -->
    <link rel="stylesheet" href="{% static 'mysite/galeria/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/galeria/style.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/galeria/css/responsive.css' %}">
    <script src="{% static 'mysite/galeria/js/vendor/modernizr-2.8.3.min.js' %}"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */


    </style>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" id="navbar" style="transition: 0.4s;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <img id='logo' src="{% static 'mysite/logo2.png' %}" alt="Turistify" style="transition: 0.4s;">

        </div>
        <div class="collapse navbar-collapse" id="myNavbar" data-target="#myNavbar">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a><span class="glyphicon glyphicon-user"></span> Hola {{ user.username }}!</a>
                    </li>
                    <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {#                {% if menu is defined %}#}
                {#                    <li class="active"><a href="/">Inicio</a></li>#}
                {#                    <li><a href="/#servicios">Servicio</a></li>#}
                {#                    <li><a href="/#galeria">Galeria</a></li>#}
                {#                    <li><a href="/#contactenos">Contactenos</a></li>#}
                {#                    {% if user.is_authenticated %}#}
                {#                        <li><a href="/report">Reportes</a></li>#}
                {#                    {% endif %}#}
                {#                {% endif %}#}
                {% if menu %}
                    <li class="active"><a href="#index">Inicio</a></li>
                    <li><a href="#servicios">Servicio</a></li>
                    <li><a href="#galeria">Galeria</a></li>
                    <li><a href="#contactenos">Contactenos</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="/report">Reportes</a></li>
                    {% endif %}
                {% else %}
                    <li class="active"><a href="/">Inicio</a></li>
                    <li><a href="/#servicios">Servicio</a></li>
                    <li><a href="/#galeria">Galeria</a></li>
                    <li><a href="/#contactenos">Contactenos</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="/report">Reportes</a></li>
                    {% endif %}
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

<div id="content">{% block content %}{% endblock %}</div>


<br><br>
<footer class="container-fluid text-center navbar-inverse">
    {#    <ul class="list-inlin">#}
    {#        <li class="list-inline-item">#}
    {#            <a href="#" target="_blank">Descubre Guayaquil</a>#}
    {#        </li>#}
    {#        <li class="list-inline-item">#}
    {#            <a href="#" target="_blank">Dónde Ir</a></li>#}
    {#        <li class="list-inline-item">#}
    {#            <a href="#" target="_blank">Planea tu viaje</a></li>#}
    {#        <li class="list-inline-item">#}
    {#            <a href="#" target="_blank">Guayaquil 360°</a></li>#}
    {#        <li class="list-inline-item">#}
    {#            <a href="#" target="_blank">Inicio</a></li>#}
    {##}
    {#    </ul>#}
    <div class="row ">
        <ul class="list-inline">
            <li class="list-inline-item"><a href="#index">Inicio</a></li>
            <li class="list-inline-item"><a href="#servicios" >Servicios</a></li>
            <li class="list-inline-item"><a href="#galeria" >Galeria</a></li>
            <li class="list-inline-item"><a href="#contactenos" >Contactenos</a></li>
            <li class="list-inline-item"><a href="{% url 'login' %}" >Login</a></li>
        </ul>
    </div>
    <div class="row row-copirayt">
        <p class="mbr-text mb-0 mbr-fonts-style mbr-white align-center display-7">
            © Copyright 2018 MSIG - Todos los Derechos Reservados
        </p>
    </div>
</footer>
{% load static %}
<script>
    // When the user scrolls down 80px from the top of the document, resize the navbar's padding and the logo's font size
    window.onscroll = function () {
        scrollFunction()
    };

    function scrollFunction() {
        if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
            document.getElementById("navbar").style.opacity = "0.8";
            document.getElementById("logo").style.width = "150px";
            document.getElementById("logo").style.paddingTop = "8px";
        } else {
            {#            document.getElementById("myNavbar").style.padding = "18px 10px";#}
            document.getElementById("navbar").style.opacity = "1";
            document.getElementById("logo").style.width = "183px";
            document.getElementById("logo").style.paddingTop = "0px";
        }
    }
</script>
<!--Vendor-JS-->
<script src="{% static 'mysite/galeria/js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'mysite/galeria/js/vendor/bootstrap.min.js' %}"></script>
<!--Plugin-JS-->
<script src="{% static 'mysite/galeria/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'mysite/galeria/js/appear.js' %}"></script>
<script src="{% static 'mysite/galeria/js/bars.js' %}"></script>
<script src="{% static 'mysite/galeria/js/waypoints.min.js' %}"></script>
<script src="{% static 'mysite/galeria/js/counterup.min.js' %}"></script>
<script src="{% static 'mysite/galeria/js/easypiechart.min.js' %}"></script>
<script src="{% static 'mysite/galeria/js/mixitup.min.js' %}"></script>
<script src="{% static 'mysite/galeria/js/contact-form.js' %}"></script>
<script src="{% static 'mysite/galeria/js/scrollUp.min.js' %}"></script>
<script src="{% static 'mysite/galeria/js/magnific-popup.min.js' %}"></script>
<script src="{% static 'mysite/galeria/js/wow.min.js' %}"></script>

<script src="{% static 'mysite/galeria/js/main.js' %}"></script>

</body>
</html>

templates/contactenos.html
{#{% extends "base.html" %}#}
{#{% block title %}Inicio{% endblock %}#}
{#{% block content %}#}
{#    {% load static %}#}
<section class="section-padding" id="contactenos">
    <div class="container" >
        <div class="jumbotron">
            <div class="row">
                <div class="col-sm-12 form-groupcol-md-8 col-xs-12 col-sm-6 col-lg-8">
                    <div class="container" style="border-bottom:1px solid black">
                        <h2>Contáctenos</h2>
                    </div>
                    <hr>
                    <p>
                        Envíanos tu mensaje y te responderemos lo antes posible.
                    </p>
                    <form role="form" method="post" id="reused_form">
                        <div class="row">
                            <div class="col-sm-6 form-group">
                                <label for="name">
                                    Primer Nombre:</label>
                                <input type="text" class="form-control" id="firstname" name="firstname" maxlength="50">
                            </div>
                            <div class="col-sm-6 form-group">
                                <label for="name">
                                    Apellido:</label>
                                <input type="text" class="form-control" id="lastname" name="lastname" maxlength="50">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 form-group">
                                <label for="email">
                                    Email:</label>
                                <input type="text" class="form-control" id="email" name="email"
                                       maxlength="50">
                            </div>
                            <div class="col-sm-6 form-group">
                                <label for="email">
                                    Teléfono:</label>
                                <input type="tel" class="form-control" id="phone" name="phone" required
                                       maxlength="50">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 form-group">
                                <label for="name">
                                    Mensaje:</label>
                                <textarea class="form-control" type="textarea" id="message" name="message"
                                          placeholder="Your Message Here" maxlength="6000" rows="7"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 form-group">
                                <button onclick="location.href = '/';" type="submit"
                                        class="bttn bttn-primary" id="btnContactUs">Enviar !
                                </button>
                            </div>
                        </div>

                    </form>
                </div>

                <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                    <hr>
                    <hr>
                    <ul class="container details">
                        <li><p><span class="glyphicon glyphicon-earphone one" style="width:50px;"></span>593 983761039
                        </p></li>
                        <li><p><span class="glyphicon glyphicon-envelope one" style="width:50px;"></span>info@turistify.com
                        </p></li>
                        <li><p><span class="glyphicon glyphicon-map-marker one" style="width:50px;"></span>Matriz:
                            Malecón 2000</p></li>
                        <li><p><span class="glyphicon glyphicon-map-marker one" style="width:50px;"></span>Sucursal 1:
                            Mall del Sol</p></li>
                        <li><p><span class="glyphicon glyphicon-map-marker one" style="width:50px;"></span>Sucursal 2:
                            Mall del Sur</p></li>
                        <li><p><span class="glyphicon glyphicon-new-window one" style="width:50px;"></span><a href="#">www.turistify.com
                        </a></p></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{#{% endblock %}#}

templates/galeria.html
<section class="section-padding" id="galeria">
    {% load static %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                <div class="page-title text-center">
                    <h2 class="title">Galería</h2>
                    <p>Te invitamos a visitar nuestras diferentes categorías en nuestra galería</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <!-- Mixitup controls -->
                <ul class="filter-controls text-center">
                    <li class="active filter" data-filter="all">All</li>
                    <li class="active filter" data-filter=".graphics">Postales</li>
                    <li class="filter" data-filter=".ux_ui">Monumentos</li>
                    <li class="filter" data-filter=".web_design">Sitios Turisticos</li>
                    <li class="filter" data-filter=".coding">Restaurantes</li>
                    <li class="filter" data-filter=".developing">Gastronomía</li>
                    <li class="filter" data-filter=".photography">Diversión</li>
                </ul>
            </div>
        </div>
        <div class="row" id="filtering">
            <div class="col-xs-6 col-sm-4 col-md-3 mix  web_design">
                <div class="filter-box">
                    <div class="filter-image">
{#                        <img src="{% static '#}
                        <img src="{% static 'mysite/galeria/images/work-1.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Arquitectura</h5>
                        <a href="{% static 'mysite/galeria/images/work-1.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix coding ">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-2.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Restaurantes</h5>
                        <a href="{% static 'mysite/galeria/images/work-2.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix ux_ui ">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-3.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Monumentos</h5>
                        <a href="{% static 'mysite/galeria/images/work-3.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix web_design">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-4.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Iglesias</h5>
                        <a href="{% static 'mysite/galeria/images/work-4.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix  developing">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-5.jpg'%}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Gastronomía</h5>
                        <a href="{% static 'mysite/galeria/images/work-5.jpg'% }" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix graphics">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-6.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Postales</h5>
                        <a href="{% static 'mysite/galeria/images/work-6.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix  photography">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-17.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Diversión</h5>
                        <a href="{% static 'mysite/galeria/images/work-17.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix web_design graphics">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-8.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Postales</h5>
                        <a href="{% static 'mysite/galeria/images/work-8.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
             <div class="col-xs-6 col-sm-4 col-md-3 mix ux_ui">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-9.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Monumentos</h5>
                        <a href="{% static 'mysite/galeria/images/work-9.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix developing">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-12.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Gastronomía</h5>
                        <a href="{% static 'mysite/galeria/images/work-12.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix ux_ui">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-13.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Monumentos</h5>
                        <a href="{% static 'mysite/galeria/images/work-13.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix developing">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-11.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Gastronomía</h5>
                        <a href="{% static 'mysite/galeria/images/work-11.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix photography">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-7.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Diversión</h5>
                        <a href="{% static 'mysite/galeria/images/work-7.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix coding">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-19.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Restaurantes</h5>
                        <a href="{% static 'mysite/galeria/images/work-19.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix web_design">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-20.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Sitios Turisticos</h5>
                        <a href="{% static 'mysite/galeria/images/work-20.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3 mix coding">
                <div class="filter-box">
                    <div class="filter-image">
                        <img src="{% static 'mysite/galeria/images/work-21.jpg' %}" alt="">
                    </div>
                    <div class="filter-hover">
                        <h5>Restaurantes</h5>
                        <a href="{% static 'mysite/galeria/images/work-21.jpg' %}" class="filter-popup" data-effect="mfp-zoom-in"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Portfolio-Area / -->

templates/image.html
{% extends "base.html" %}
{% block title %}Imagenes{% endblock %}
{% block content %}
    <section class="section-table cid-r28jHQ8Sqt" id="image">
        <style>
            #imagen {
                border: 1px solid black;
                margin: 5px;
                height: 405px;
                padding: 5px;
            }

            h3 {
                text-align: center;
            }

            img {
                float: left;
                margin: 0px 15px 15px 0px;
            }
        </style>
        {% for item in items %}
            <div id="imagen">
                <h3>{{ item.title }}</h3>
                {{ item.description|safe }}<br/>
                <h4>{{ item.author }}</h4>
                {{ item.date_taken }}
            </div>
        {% endfor %}
    </section>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Inicio{% endblock %}
{% block content %}
    {% load static %}
    <div class="jumbotron container-fluid nopadding" id="index">
        {#        <div class="container">#}
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    {% load static %}
                    <img src="{% static 'mysite/1.jpg' %}" alt="Los Angeles" style="width:100%;">
                </div>

                <div class="item">
                    <img src="{% static 'mysite/2.jpg' %}" alt="Chicago" style="width:100%;">
                </div>

                <div class="item">
                    <img src="{% static 'mysite/3.jpg' %}" alt="New york" style="width:100%;">
                </div>
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        {#        </div>#}
    </div>
    {% include 'servicio.html' %}
    {% include 'galeria.html' %}
    <div class="container-fluid">
        <div class="row center">
            <div class="col-md-6 mt64 mb32">
                <h3 style="text-align:center">GUAYAQUIL ES MI DESTINO</h3>
                <h3 style="text-align:center">Sitio web oficial turístico de Guayaquil. Los esperamos con los brazos abiertos, porque somos un puerto abrigado que recibe con amor a todos los turistas que llegan desde diversas partes del mundo.<br/></h3>
                <h3 style="text-align: right;">
                    <br/>
                </h3>

                <p style="text-align: right;">&nbsp;</p>
            </div>
            <div class="col-md-6 mb32 mt92">
                <img class="img img-responsive mb16" src="{% static 'mysite/logo3.png' %}"/>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-3 text-center">

        <div class="row">
            <div class="col-sm-6">
                <h2 class="title">Sucursales</h2>
                <div id="map" class="col-xs-2"></div>
                <script src="{% static 'mysite/maps/mapa2.js' %}"></script>
                <script async defer
                        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYbbWh-wg7ZhBtlIoRVanl45pILiKSiP0&callback=initMap">
                </script>
            </div>
            <div class="col-sm-6">
                <h2 class="title">Visítanos</h2>
                <iframe id="video" width="100%" height="315" src="https://www.youtube.com/embed/rT8QAFNuXTM"
                        allowfullscreen></iframe>
            </div>
        </div>
    </div>
    {% include 'contactenos.html' %}
    <script>
        $(document).ready(function () {
            // Add scrollspy to <body>
            $('body').scrollspy({target: ".navbar", offset: 50});

            // Add smooth scrolling on all links inside the navbar
            $("#myNavbar a").on('click', function (event) {
                // Make sure this.hash has a value before overriding default behavior
                if (this.hash !== "") {
                    // Prevent default anchor click behavior
                    event.preventDefault();

                    // Store hash
                    var hash = this.hash;

                    // Using jQuery's animate() method to add smooth page scroll
                    // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
                    $('html, body').animate({
                        scrollTop: $(hash).offset().top
                    }, 800, function () {

                        // Add hash (#) to URL when done scrolling (default click behavior)
                        window.location.hash = hash;
                    });
                }  // End if
            });
        });
</script>

{% endblock %}

templates/report.html
{% extends "base.html" %}
{% block title %}Reportes{% endblock %}
{% block content %}
    {% load static %}
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="{% static 'mysite/graph.js' %}"></script>

    <div class="container-fluid center">
{#    <h1 id="report_title"></h1>#}
    </div>

    <div class="container-fluid" style="margin-top: 50px;">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-3 col-xl-3 graph">
                <div id="map_report"></div>
            </div>
            <div id="graph1" class="col-xs-12 col-sm-6 col-md-4  graph" data-url="{% url 'mysite:data1' %}">
                {#            <div id="graph1" class="col-sm-6 graph">#}
            </div>
            <div id="graph2" class="col-xs-12 col-sm-12 col-md-5 col-xl-5 graph" data-url="{% url 'mysite:data2' %}">
            </div>
            <script src="{% static 'mysite/maps/map_report.js' %}"></script>
            <script async defer
                    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYbbWh-wg7ZhBtlIoRVanl45pILiKSiP0&callback=initMap">
            </script>
        </div>
    </div>
    <div class="container-fluid bg-6 text-center">
        <div class="row">
            <div id="graph3" class="col-xs-12 col-sm-6 col-md-6 col-xl-6 graph" data-url="{% url 'mysite:data3' %}">
            </div>
            <div id="graph4" class="col-xs-12 col-sm-6 col-md-6 col-xl-6 graph" data-url="{% url 'mysite:data4' %}">
            </div>
        </div>
    </div><br>

{% endblock %}